# Generated by Django 5.2 on 2025-08-18 20:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresa', '0002_remove_empresas_contrato_suporte_ativo'),
        ('equipamento', '0003_remove_equipamento_empresa_alter_equipamento_gateway_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Atendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problema', models.CharField(max_length=200)),
                ('descricao_detalhada', models.TextField()),
                ('status', models.CharField(choices=[('Nao iniciado', 'Não iniciado'), ('Em andamento', 'Em andamento'), ('Aguardando retorno do cliente', 'Aguardando retorno do cliente'), ('Aguardando acesso ao servidor', 'Aguardando acesso ao servidor'), ('Concluido', 'Concluído')], default='Nao iniciado', max_length=50)),
                ('urgencia', models.CharField(choices=[('Urgente', 'Urgente'), ('Atencao', 'Atenção'), ('Moderado', 'Moderado'), ('Nao urgente', 'Não urgente')], default='Moderado', max_length=20)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('prazo', models.DateField()),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.empresas')),
                ('equipamento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipamento.equipamento')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data_criacao'],
            },
        ),
    ]
