# Generated by Django 4.0.2 on 2022-02-09 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresa', '0002_remove_empresas_contrato_suporte_ativo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_equipamento', models.CharField(max_length=30)),
                ('rodovia', models.CharField(max_length=50)),
                ('km', models.CharField(max_length=10)),
                ('sentido', models.CharField(max_length=30)),
                ('ip', models.CharField(blank=True, max_length=15)),
                ('mascara', models.CharField(blank=True, max_length=15)),
                ('gateway', models.CharField(blank=True, max_length=15)),
                ('ip_buffer', models.CharField(blank=True, max_length=15)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.empresas')),
            ],
        ),
    ]
