# Generated by Django 5.2 on 2025-08-18 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamento', '0002_alter_equipamento_empresa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipamento',
            name='empresa',
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='gateway',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='ip',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='ip_buffer',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='mascara',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='sentido',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
