# Generated by Django 4.0.1 on 2022-01-27 00:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('contrato_suporte_ativo', models.BooleanField(default=False)),
                ('tipo_contrato', models.CharField(blank=True, max_length=30)),
                ('data_de_cadastro', models.DateField(default=datetime.date.today)),
                ('data_final_contrato', models.DateField(blank=True, null=True)),
                ('responsavel_manutencao', models.CharField(blank=True, max_length=30)),
                ('telefone_responsavel', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'verbose_name': 'Empresa',
            },
        ),
    ]
