# Generated by Django 4.0.1 on 2022-02-08 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresas',
            name='contrato_suporte_ativo',
        ),
    ]
