# Generated by Django 4.0.1 on 2022-01-07 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='concessionarias',
            options={'verbose_name': 'Concessionaria'},
        ),
        migrations.AlterField(
            model_name='concessionarias',
            name='data_final_contrato',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='concessionarias',
            name='nome',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='concessionarias',
            name='responsavel_manutencao',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='concessionarias',
            name='telefone_responsavel',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='concessionarias',
            name='tipo_contrato',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
