# Generated by Django 4.0.1 on 2022-01-07 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0002_alter_concessionarias_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='concessionarias',
            name='data_cadastro',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='concessionarias',
            name='nome',
            field=models.CharField(max_length=100),
        ),
    ]
