# Generated by Django 4.0.1 on 2022-01-07 15:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0003_concessionarias_data_cadastro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concessionarias',
            name='data_cadastro',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='concessionarias',
            name='data_final_contrato',
            field=models.DateField(blank=True, null=True),
        ),
    ]
