# Generated by Django 4.0.1 on 2022-01-20 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0004_alter_concessionarias_data_cadastro_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Concessionarias',
            new_name='Empresas',
        ),
        migrations.AlterModelOptions(
            name='empresas',
            options={'verbose_name': 'Empresa'},
        ),
    ]
